
description: Desenvolvimento e Gerenciamento de Software
meta_description: "Mauricio Fritsch, gerenciamento de desenvolvimento de Software"
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mauricionik.github.io'
google_analytics: 'UA-58884601-1'

# Details for the RSS feed generator
url:            'http://mauricionik.github.io/'
author:
    name: 'Maur√≠cio Fritsch'
    thumb: '/assets/images/poker_face.jpg'
    url:
        facebook: 'https://www.facebook.com/mauricionik'
        twitter: 'https://twitter.com/mauricionik'
        email: 'mauricio.nik@hotmail.com'

urls:
    about: '/sobre'
    
img_path: '/assets/images/'
